### ISSUE TITLE
Didn't receive faucet

### ISSUE THREAD

**Issue by DeluneClaire** [gear-foundation/vara-network#1]
### Problem

I was trying to receive the faucet, but it was unsuccessful.

### Steps

1. I have inserted my email and my name and after I logged in I wanted to receive the faucet. 
2. Once I clicked on the faucet it directed me to the page but my balance was 0, even though it says claimed.
3.

### Expected Behavior

I've expected to receive faucet...

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

<img width="631" alt="Snímek obrazovky 2023-09-01 v 16 41 33" src="https://github.com/gear-foundation/vara-network/assets/104791453/dda45098-a997-47f6-9962-b32bbec9c8ee">

<img width="464" alt="Snímek obrazovky 2023-09-01 v 16 49 57" src="https://github.com/gear-foundation/vara-network/assets/104791453/8858f9dd-980a-4543-8abe-0033941cce8b">

**Comment by shamilsan** [comment]
We have fixed this problem. Please try again and reopen this issue if the problem persists.
