### ISSUE TITLE
NFT Minting Issue

### ISSUE THREAD

**Issue by umeshjaiswal32** [gear-foundation/vara-network#12]
### Problem

I have successfully claimed the faucet and registered for the testnet but while trying to mint the NFT, it shows "You are currently not part of the Vara Network Testnet." 

### Steps

1. N/A
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot 2023-09-02 045302](https://github.com/gear-foundation/vara-network/assets/118675185/50964524-36e9-4289-8129-14225feb23da)

**Comment by shamilsan** [comment]
Please see #2.

**Comment by umeshjaiswal32** [comment]
There is no any solution for the issue on #2

**Comment by shamilsan** [comment]
> There is no any solution for the issue on #2

Please try this one: https://github.com/gear-foundation/vara-network/issues/2#issuecomment-1704758589

Please don't hesitate to reopen the issue if the problem continues.
