### ISSUE TITLE
My NFT page bug

### ISSUE THREAD

**Issue by Michael0x** [gear-foundation/vara-network#2]
### Problem

After clicking "mint NFT" I received the message attached

### Steps

1. Registrate 
2. Enter https://nft.vara-network.io/
3. Message

### Expected Behavior

NFT mint

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Other browser

None

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

<img width="856" alt="Снимок экрана 2023-09-01 в 19 22 03" src="https://github.com/gear-foundation/vara-network/assets/140702682/eb972b16-61bb-4bf8-94c2-d6d845329d85">

**Comment by shamilsan** [comment]
We've resolved the issue related to the occasional absence of the minting button. In cases where the button doesn't appear immediately, it is now set to display within minutes. Additionally, we have added a message to inform users that waiting may be necessary in such instances.

**Comment by umeshjaiswal32** [comment]
Where is the solution for "You are currently not the part of the Vara Network Testnet" issue?

**Comment by shamilsan** [comment]
> Where is the solution for "You are currently not the part of the Vara Network Testnet" issue?

Please refer to this comment: https://github.com/gear-foundation/vara-network/issues/2#issuecomment-1704758589
