### ISSUE TITLE
Cant mint

### ISSUE THREAD

**Issue by oxdea** [gear-foundation/vara-network#21]
### Problem

IM join testnet done register but cant mint, how to solved please..

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Kiwi browser 

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_2023-09-02-18-53-37-48_4d38fce200f96aeac5e860e739312e76](https://github.com/gear-foundation/vara-network/assets/41576216/c6eae36a-1406-4302-b96e-8911d3d2e060)

**Comment by shamilsan** [comment]
You seem to have chosen the wrong network. We recommend using desktop browsers (Firefox or Chrome) for better user experience. Please try again using the desktop and reopen the issue if the problem remains.

**Comment by oxdea** [comment]
Still trying play sir... Nft done minted
Tyvm

Pada tanggal Sel, 5 Sep 2023 13.56, Shamil ***@***.***>
menulis:

**Comment by oxdea** [comment]
Nft done minted sir.. trying play game now.. tyvm
