### ISSUE TITLE
Tic-Tac-Toe game error

### ISSUE THREAD

**Issue by ygd58** [gear-foundation/vara-network#24]
### Problem

Tic Tac Toe game I tested the game and the wallet transaction does not come before the time passes and sometimes the wallet transactions do not come when making moves and both the amount of test tokens is decreasing and the test token is decreasing even though the transaction does not take place.

### Steps

1.activities
2.Mint an NFT
3.Tic-Tac-Toe game

### Expected Behavior

increasing the time duration in the game or the lack of time can make the game more comfortable to play otherwise the operations are delayed and the game is not played

### Your Substrate Address

5HQM7JkaP177JPXXTbBWksxSHv8DCfSyRaQEU6x7GiV1PVWJ

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Notes

the problem is that the network and the platform is too dense to give rpc error, I tested it with different wallets and by changing the browser, I still got the same errors, I think it is caused by the website

**Comment by shamilsan** [comment]
We have added more nodes to the network; please try again, and don't hesitate to reopen this issue if the problem persists.
