### ISSUE TITLE
cannot mint my nft

### ISSUE THREAD

**Issue by indosiarr** [gear-foundation/vara-network#25]
### Problem

i can't mint nft

### Steps

1.Register
2.Activities
3.Mint an NFT
4.You don't have NFT yet

### Your Substrate Address

5CVH4DUAKp2rVktyH5kiWHgSr2U9zzLnsUtEQMuchqkntJ8i

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Screenshot 2023-09-03 002858](https://github.com/gear-foundation/vara-network/assets/88529731/c5179523-02de-40d7-9e6a-7306d90018ea)

### Notes

please fix it

**Comment by shamilsan** [comment]
You may need to wait some time before the NFT appears.
Please reopen the issue if the problem remains.
