### ISSUE TITLE
Bug with RPC node: timeout after 60s

### ISSUE THREAD

**Issue by Bayunur10** [gear-foundation/vara-network#3]
### Problem

Mint nft  not working
I'm use device android version 11
Browser: mises browser
Wallet: subwallet extension
Address wallet : 5HmTZLK3YtD5CVHxQwkfrw5RGPfmrEGb3tkfYbdohQsxiiF9

### Steps

1.mint nft failled
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Other browser

Mises browser

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Screenshot_20230901-225331](https://github.com/gear-foundation/vara-network/assets/142322829/5fa75608-6bc2-4c4b-8d50-1f67e0397ea5)

**Comment by shamilsan** [comment]
This issue has been fixed; please try again and reopen the issue if the problem remains.
