### ISSUE TITLE
Discord name showing incorrectly and NFT minting issue

### ISSUE THREAD

**Issue by duralengin** [gear-foundation/vara-network#34]
### Problem

My discord name looks different than when I first saved it and I can't change it. I can't mint NFT.

### Steps

1.Enter Activities
2.Mint an Nft

1- edit wallet name
2-enter the wallet name
3- save

### Expected Behavior

Minting the NFT

discord step entered correctly

### Your Substrate Address

5CXFZrPN74RErG5ny69ZRDELJ2tjywVX1pXuRjp3wR6s5t2E

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![v1](https://github.com/gear-foundation/vara-network/assets/96820155/017462ec-e8c1-406c-81f8-18c45e27d043)
![v2](https://github.com/gear-foundation/vara-network/assets/96820155/3ee8b173-6af6-439e-9ddb-4f42cd9cab78)

**Comment by shamilsan** [comment]
This `#0` suffix is for the new format of Discord nicknames. For the second question, please refer to #2.
