### ISSUE TITLE
Tic Tac Toe game playing time transcation approve but showing balance low

### ISSUE THREAD

**Issue by iqra-dao** [gear-foundation/vara-network#36]
### Problem

when im playing Tic Tac Toe game then when submit transcation approve but showing balance low

### Steps

1.Tic Tac Toe game
2.submit transcation 
3.showing balance low but i have alredy balance

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot (1171)](https://github.com/gear-foundation/vara-network/assets/85840039/23492f78-8bc5-4f20-873e-1c5cee1e2e3f)

**Comment by shamilsan** [comment]
This situation may appear when you try to play again before your last turn has been processed.
