### ISSUE TITLE
Race car cannot be approved

### ISSUE THREAD

**Issue by gawiar** [gear-foundation/vara-network#37]
### Problem

car race games cannot be approved. loading takes too long and ends up failing

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

**Comment by shamilsan** [comment]
We have added more nodes to the network, please try again and feel free to reopen this issue if the problem persists.
