### ISSUE TITLE
Facing `User not found by pubKey` error

### ISSUE THREAD

**Issue by SecretPlus** [gear-foundation/vara-network#4]
### Problem

![Screenshot_3](https://github.com/gear-foundation/vara-network/assets/35276321/c0cb9c3b-6e58-4fd9-8bf8-8766756b0597)

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [x] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [x] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

**Comment by shamilsan** [comment]
You seem to register with one address and be logged in with another address. Please use the same address in your wallet when registering and logging in.
