### ISSUE TITLE
Internal Error. Tokens haven't been sent. Please try again later

### ISSUE THREAD

**Issue by ygd58** [gear-foundation/vara-network#40]
### Problem

Internal Error. Tokens haven't been sent. Please try again later I can't claim tokens from faucet and new invitation link is constantly created and new invitation link is given and I can't claim tokens from the users I invited

### Steps

1.faucet
2.error
3.Internal Error. Tokens haven't been sent. 

### Your Substrate Address

5HQM7JkaP177JPXXTbBWksxSHv8DCfSyRaQEU6x7GiV1PVWJ

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [X] Talisman
- [X] Nova Wallet
- [X] SubWallet

### Screenshots

![error](https://github.com/gear-foundation/vara-network/assets/78954051/702bd4db-6e2e-44fc-8d4b-f2ce7dd38b85)

**Comment by shamilsan** [comment]
As I see from the screenshot, the claim attempts count hasn't been decreased. So you can try to claim again.
