### ISSUE TITLE
i cant connect testnet page

### ISSUE THREAD

**Issue by unfatalih** [gear-foundation/vara-network#41]
### Problem

When I try to connect to the testnet page, I get the error '8000:Runtime error:"Program not found"'

### Steps

1.i opened testnet page(https://incentivized.vara-network.io/)
2.connected talisman wallet
3. I get the error '8000:Runtime error:"Program not found"'
4. Leaderboard, Faucet, Activities and Swap tabs not loaded

### Your Substrate Address

5E1dqvpcDrZU3WPQ732TPJY4iQNxbTpLDXzaRDn2oXqqLG3F

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Brave

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![vara error](https://github.com/gear-foundation/vara-network/assets/72918026/4c4b150e-e608-48d0-b590-3543ef47b03a)

**Comment by shamilsan** [comment]
Yes, we have redeployed some parts. Please reload the page; now it should work.
