### ISSUE TITLE
Mantra wallet pop up each time

### ISSUE THREAD

**Issue by Debbiemation** [gear-foundation/vara-network#42]
### Problem

I just tried to join the testnet but I keep getting error message 

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [X] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![image](https://github.com/gear-foundation/vara-network/assets/61961723/f886328a-fabd-4019-b19f-d6e21a715c60)

![image](https://github.com/gear-foundation/vara-network/assets/61961723/2cea2eb4-c6bd-4261-b789-d336d245ac36)

### Notes

Kindly check out this issues, so I can continue my tasks

**Comment by shamilsan** [comment]
I can't see the error message behind the Talisman window. Could you please share the error message?

**Comment by shamilsan** [comment]
@Debbiemation Could you please share more details?

**Comment by shamilsan** [comment]
Please reopen the issue if the problem persists.
