### ISSUE TITLE
extrinsic failed

### ISSUE THREAD

**Issue by Sokkrates** [gear-foundation/vara-network#43]
### Problem

fee cuts but all my transactions are negative

### Steps

1.
2.
3.

### Your Substrate Address

0x867ffd0706bde2a5ad8eca4a765b74ce43c26ced762c40dd28159b268f555045

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![vara hata](https://github.com/gear-foundation/vara-network/assets/101201028/7282da72-f4ea-4a33-872a-d49a848ffa58)

**Comment by shamilsan** [comment]
Please check that you have more than 250 TVARA before swap. If you have less than that amount, you can use your referral link to invite other people and earn additional TVARA.
