### ISSUE TITLE
Invalid registration link token

### ISSUE THREAD

**Issue by sdx012** [gear-foundation/vara-network#44]
### Problem

I can not register for the testnet . 

### Steps

1. In the register page click sign up and error pops up
2.
3.

### Your Substrate Address

5C8SvLtNx2UhoQXnFYvSYyVnEQsEZGYNQhjwNj2X5QFMsdnF

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [X] Other

### Other browser

Brave

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

**Comment by shamilsan** [comment]
The reason is that the referral link reached the max number of users.
The solution is to request a new referral link.
