### ISSUE TITLE
You are currently not part of the Vara Network Testnet.

### ISSUE THREAD

**Issue by halililbay** [gear-foundation/vara-network#5]
### Problem

You are currently not part of the Vara Network Testnet.

![image](https://github.com/gear-foundation/vara-network/assets/107258543/cd90772b-1a58-42fa-9290-68c39f13ab82)

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![image](https://github.com/gear-foundation/vara-network/assets/107258543/a0167e98-bb6d-4cc6-86e7-725732b4d2fb)

**Comment by lopiwindu** [comment]
![image](https://github.com/gear-foundation/vara-network/assets/80633898/fcf84c45-b3c4-47ff-8a83-7361e345d2b9)

Chrome and wallet talisman

**Comment by Troublesht** [comment]
Same issue 
Using Chrome browser 
polkadot wallet

**Comment by shamilsan** [comment]
Please see #2.

**Comment by umeshjaiswal32** [comment]
where is the solution? Why closing issue without any solution?

**Comment by shamilsan** [comment]
> where is the solution? Why closing issue without any solution?

Let me copy it here for you.

> We've resolved the issue related to the occasional absence of the minting button. In cases where the button doesn't appear immediately, it is now set to display within minutes. Additionally, we have added a message to inform users that waiting may be necessary in such instances.
