### ISSUE TITLE
nft cannot mint?

### ISSUE THREAD

**Issue by emrecetin03** [gear-foundation/vara-network#6]
### Problem

Mint is not made even though I bought tokens from faucet

### Steps

1.I minted a token from faucet
2.it says you are not eligible for nft minti
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [ ] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [X] SubWallet

### Screenshots

![Ekran görüntüsü 2023-09-01 185817](https://github.com/gear-foundation/vara-network/assets/101176535/8dbe238f-6065-491b-8458-8f584ec22e08)

### Notes

please help me 
mail: djdifficult@hotmail.com

**Comment by hoptedix** [comment]
Hi I have  same problem,did it solve ?

**Comment by shamilsan** [comment]
Please see #2.
