### ISSUE TITLE
NFT problem

### ISSUE THREAD

**Issue by Marilyn69** [gear-foundation/vara-network#7]
### Problem

NFT page has problem, I can't mint it.

### Steps

1.
2.
3.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other

### Which wallet you are using?

- [X] PolkadotJS
- [ ] Talisman
- [ ] Nova Wallet
- [ ] SubWallet

### Screenshots

![Screenshot_3](https://github.com/gear-foundation/vara-network/assets/100492684/d5b69cbe-d298-410c-81cb-f24c56601945)

wallet address: 0xc01acab0280b3542a2d93a4bfcd7b33ee254643586a39d337dde987ab119516c

**Comment by shamilsan** [comment]
Please see #2.
